batch_size: 64
height: 32
learning_rate: 0.002
max_text_length: 31
model_path: Models/08_handwriting_recognition_torch\202406191516
train_epochs: 1000
vocab: -.01236ABCDEFGHIKLMNOPQRSTUVXZabcdefghijklmnopqrstuvwxyz
width: 128
